object Versions {
    const val kotlin = "1.5.10"
    const val appcompat = "1.3.0"
    const val constraintlayout = "2.0.4"
    const val lifecycle = "2.2.0"
    const val lifecycle_ktx = "2.3.1"
    const val activity_ktx = "1.2.3"
    const val junit = "4.13.2"
    const val ext_junit = "1.1.2"
    const val espresso = "3.3.0"
    const val hilt = "2.37"
    const val navigation = "2.3.5"
    const val interceptor = "4.9.0"
    const val retrofit = "2.9.0"
    const val glide = "4.12.0"
    const val room = "2.3.0"
    const val mockk = "1.10.6"
    const val lottie = "3.7.0"
    const val fragment = "1.3.3"
    const val paging = "3.0.0"
}